"""Tests for the analysis notebook and paper compilation.

* :class:`NotebookValidityUnitTests` — load analysis.ipynb via nbformat
  and verify it parses (catches accidental JSON corruption). No data,
  no execution.
* :class:`NotebookExecutionIntegrationTests` — execute the notebook end
  to end in a disposable tmpdir mirror tree, verify every figure the
  paper references is produced and the merged-results parquet is
  written. Never touches committed figures/tables in the real tree.
* :class:`PaperCompilationIntegrationTests` — pdflatex + bibtex in a
  disposable tmpdir mirror tree; reads committed figures and tables
  from the real tree via symlinks, writes all build artifacts to the
  tmpdir. Never touches the committed paper PDF.
"""

import os
import re
import subprocess
import tempfile
import unittest

import pytest


_REPO_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
)
_ANALYSIS_DIR = os.path.join(_REPO_ROOT, 'analysis')
_PAPER_DIR = os.path.join(_REPO_ROOT, 'paper')
_SRC_DIR = os.path.join(_REPO_ROOT, 'src')
_VENV_BIN = os.path.join(_REPO_ROOT, 'venv', 'bin')
_PDFLATEX = '/Library/TeX/texbin/pdflatex'
_BIBTEX = '/Library/TeX/texbin/bibtex'


def _missing_data_skip_message(path: str) -> str:
    """Build the skip message for a missing integration prerequisite."""
    return (
        f"Integration test requires {path}. "
        f"Either run scripts/download_data.sh to fetch the published dataset, "
        f"or regenerate the data by running the experiment pipeline."
    )


def _paper_figure_filenames() -> list[str]:
    """Parse `paper.tex` and return every `\\includegraphics` target."""
    tex_path = os.path.join(_PAPER_DIR, 'paper.tex')
    with open(tex_path) as f:
        tex = f.read()
    return sorted(set(re.findall(r'\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}', tex)))


def _paper_asset_filenames() -> set[str]:
    """Return filenames hand-shipped under `paper/assets/`.

    These are referenced by the paper but NOT generated by the
    notebook — pdflatex picks them up via the second entry in
    `\\graphicspath`. Tests that compare paper-referenced figures
    against notebook outputs need to subtract this set.

    Returns:
        Set of asset filenames, or an empty set if the assets dir
        doesn't exist.
    """
    assets_dir = os.path.join(_PAPER_DIR, 'assets')
    if not os.path.isdir(assets_dir):
        return set()
    return set(os.listdir(assets_dir))


def _build_mirror_tree(tmp_root: str, spec: dict[str, str | None]) -> None:
    """Populate `tmp_root` with symlinks to real inputs plus empty dirs.

    Used to construct a sandbox that looks like a subset of the
    real repo tree from the compiler's / nbconvert's perspective,
    so all writes land in `tmp_root` while reads follow symlinks
    to the real inputs.

    Args:
        tmp_root: Directory that will host the mirror tree.
        spec: Map from relative path inside `tmp_root` to either an
            absolute source path to symlink, or `None` to create an
            empty directory there. Parent directories are
            auto-created.
    """
    for rel, src in spec.items():
        rel = rel.rstrip('/')
        target = os.path.join(tmp_root, rel)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        if src is None:
            os.makedirs(target, exist_ok=True)
        else:
            os.symlink(src, target)


# ===========================================================================
# Unit suite
# ===========================================================================

class NotebookValidityUnitTests(unittest.TestCase):
    """analysis.ipynb is well-formed JSON conforming to nbformat."""

    def test_notebook_parses_as_nbformat(self):
        """`analysis.ipynb` parses as nbformat v4 and has more than 5 cells."""
        import nbformat

        notebook_path = os.path.join(_ANALYSIS_DIR, 'analysis.ipynb')
        self.assertTrue(os.path.exists(notebook_path), notebook_path)

        with open(notebook_path) as f:
            nb = nbformat.read(f, as_version=4)

        nbformat.validate(nb)
        self.assertGreater(len(nb.cells), 5)


# ===========================================================================
# Integration suite
# ===========================================================================

@pytest.mark.integration
class NotebookExecutionIntegrationTests(unittest.TestCase):
    """Execute analysis.ipynb in a mirror-tree tmpdir and verify outputs.

    Everything the notebook writes — figures, tables, parquet, and the
    executed notebook copy — lands in the tmpdir. Committed files in
    ``analysis/figures/`` and ``paper/tables/`` are never touched.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        notebook_path = os.path.join(_ANALYSIS_DIR, 'analysis.ipynb')
        if not os.path.exists(notebook_path):
            raise unittest.SkipTest(f"Missing notebook: {notebook_path}")

        required = [
            os.path.join(_ANALYSIS_DIR, 'human_labels.csv'),
            os.path.join(_REPO_ROOT, 'src', 'experiments', 'results'),
            os.path.join(_REPO_ROOT, 'src', 'experiments', 'results', 'experiments'),
            os.path.join(_REPO_ROOT, 'src', 'experiments', 'results', 'noise'),
            os.path.join(_REPO_ROOT, 'src', 'data', 'original-datasets', 'nq', 'corpus.jsonl'),
            os.path.join(_REPO_ROOT, 'src', 'data', 'original-datasets', 'nq', 'qrels', 'test.tsv'),
            os.path.join(_REPO_ROOT, 'src', 'data', 'experiment-datasets', 'nq-corruptrag-ak-poisoned-docs.jsonl'),
            os.path.join(_REPO_ROOT, 'src', 'data', 'experiment-datasets', 'nq-incorrect-answers-poisoned-docs.jsonl'),
        ]
        for path in required:
            if not os.path.exists(path):
                raise unittest.SkipTest(_missing_data_skip_message(path))
        cls.notebook_path = notebook_path

    def test_notebook_executes_and_produces_outputs(self):
        """Notebook runs end-to-end and emits every paper figure/table."""
        with tempfile.TemporaryDirectory(prefix='nb_exec_') as tmp_root:
            _build_mirror_tree(tmp_root, {
                'analysis/analysis.ipynb': self.notebook_path,
                'analysis/human_labels.csv': os.path.join(_ANALYSIS_DIR, 'human_labels.csv'),
                'analysis/figures': None,
                'analysis/intermediate': None,
                'src': _SRC_DIR,
                'paper/tables': None,
            })
            tmp_analysis = os.path.join(tmp_root, 'analysis')

            jupyter = os.path.join(_VENV_BIN, 'jupyter')
            result = subprocess.run(
                [
                    jupyter, 'nbconvert',
                    '--to', 'notebook',
                    '--execute',
                    '--ExecutePreprocessor.timeout=600',
                    'analysis.ipynb',
                    '--output', 'executed.ipynb',
                ],
                capture_output=True,
                text=True,
                cwd=tmp_analysis,
                env={**os.environ, 'KMP_DUPLICATE_LIB_OK': 'TRUE'},
            )
            self.assertEqual(
                result.returncode, 0,
                f"Notebook execution failed: {result.stderr[-500:]}",
            )

            tmp_figures = os.path.join(tmp_analysis, 'figures')
            generated = set(os.listdir(tmp_figures))

            # Hand-authored assets (e.g. Figma architecture diagrams) ship in
            # paper/assets/ and are out of scope for the notebook.
            asset_files = _paper_asset_filenames()
            expected = [f for f in _paper_figure_filenames() if f not in asset_files]
            self.assertGreater(len(expected), 5, "no figures parsed from paper.tex")

            missing = [f for f in expected if f not in generated]
            self.assertFalse(
                missing,
                f"Notebook didn't produce {len(missing)} paper-referenced figure(s): {missing}",
            )

            parquet_path = os.path.join(tmp_analysis, 'intermediate', 'merged_results.parquet')
            self.assertTrue(os.path.exists(parquet_path), parquet_path)

            # Tables are \input{...}'d by the paper; every .tex the
            # paper asks for must be produced by the notebook.
            tmp_tables = os.path.join(tmp_root, 'paper', 'tables')
            expected_tables = set(os.listdir(os.path.join(_PAPER_DIR, 'tables')))
            generated_tables = set(os.listdir(tmp_tables))
            missing_tables = expected_tables - generated_tables
            self.assertFalse(
                missing_tables,
                f"Notebook didn't produce expected table(s): {sorted(missing_tables)}",
            )


@pytest.mark.integration
class PaperCompilationIntegrationTests(unittest.TestCase):
    """Full bibtex-aware compile in a mirror-tree tmpdir.

    Build sequence: pdflatex → bibtex → pdflatex → pdflatex. All
    artifacts (.aux, .log, .bbl, .blg, .pdf, .out) land in the
    tmpdir. Committed figures and tables are read via symlinks.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        tex_file = os.path.join(_PAPER_DIR, 'paper.tex')
        if not os.path.exists(tex_file):
            raise unittest.SkipTest(f"Missing TeX source: {tex_file}")
        if not os.path.exists(_PDFLATEX):
            raise unittest.SkipTest(f"pdflatex not installed at {_PDFLATEX}")
        if not os.path.exists(_BIBTEX):
            raise unittest.SkipTest(f"bibtex not installed at {_BIBTEX}")

        figures_dir = os.path.join(_ANALYSIS_DIR, 'figures')
        if not os.path.isdir(figures_dir):
            raise unittest.SkipTest(_missing_data_skip_message(figures_dir))

        generated = set(os.listdir(figures_dir))
        # Hand-authored assets (e.g. Figma architecture diagrams) live in
        # paper/assets/, not analysis/figures/ — pdflatex resolves them via
        # the second entry in \graphicspath.
        asset_files = _paper_asset_filenames()
        missing = [
            f for f in _paper_figure_filenames()
            if f not in generated and f not in asset_files
        ]
        if missing:
            raise unittest.SkipTest(
                _missing_data_skip_message(
                    f"{figures_dir} (missing: {missing[:3]}{'...' if len(missing) > 3 else ''})"
                )
            )

        cls.tex_file = tex_file

    def test_paper_compiles_and_produces_pdf(self):
        """`paper.tex` compiles via pdflatex+bibtex with no errors."""
        tex_basename = os.path.basename(self.tex_file)
        stem = os.path.splitext(tex_basename)[0]

        with tempfile.TemporaryDirectory(prefix='paper_build_') as tmp_root:
            _build_mirror_tree(tmp_root, {
                f'paper/{tex_basename}': self.tex_file,
                'paper/references.bib': os.path.join(_PAPER_DIR, 'references.bib'),
                'paper/tables': os.path.join(_PAPER_DIR, 'tables'),
                'paper/assets': os.path.join(_PAPER_DIR, 'assets'),
                'analysis/figures': os.path.join(_ANALYSIS_DIR, 'figures'),
            })
            tmp_paper = os.path.join(tmp_root, 'paper')
            log_path = os.path.join(tmp_paper, f'{stem}.log')

            def run_pdflatex(pass_num: int):
                """Run one pdflatex pass; assert no `! ` fatals."""
                result = subprocess.run(
                    [_PDFLATEX, '-interaction=nonstopmode', tex_basename],
                    capture_output=True, text=True, cwd=tmp_paper,
                )
                if result.returncode != 0:
                    fatal = []
                    if os.path.exists(log_path):
                        with open(log_path) as f:
                            fatal = [l for l in f if l.startswith('! ')]
                    self.assertFalse(
                        fatal,
                        f"Fatal LaTeX errors on pdflatex pass {pass_num}: {fatal[:5]}",
                    )

            # Pass 1: produces .aux with \citation entries for bibtex.
            run_pdflatex(1)

            # bibtex: consumes .aux, writes .bbl.
            bib_result = subprocess.run(
                [_BIBTEX, stem],
                capture_output=True, text=True, cwd=tmp_paper,
            )
            self.assertEqual(
                bib_result.returncode, 0,
                f"bibtex failed (rc={bib_result.returncode}): "
                f"{bib_result.stdout}\n{bib_result.stderr}",
            )

            # Pass 2: picks up .bbl to resolve \cite{...}. Pass 3:
            # resolves forward references (page numbers in citations)
            # now that the bibliography has changed the page layout.
            run_pdflatex(2)
            run_pdflatex(3)

            # pdflatex does not exit non-zero on undefined citations
            # — it just emits a warning and prints '[?]'. Scan the
            # log so a missing bibtex entry is a real test failure.
            with open(log_path) as f:
                log_lines = f.readlines()
            undefined_cites = [
                l.strip() for l in log_lines
                if 'Citation' in l and 'undefined' in l
            ]
            self.assertFalse(
                undefined_cites,
                f"Undefined citations after bibtex: {undefined_cites[:5]}",
            )

            pdf_path = os.path.join(tmp_paper, f'{stem}.pdf')
            self.assertTrue(os.path.exists(pdf_path), pdf_path)
